<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<style>
    p {
        font-size: 2rem;
    }
</style>

    <div class="container my-5">
        <div class="row g-5 align-items-center my-5">
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.1s" src="/MVC/images/Spicy_Ademame.png" style="visibility: visible; animation-delay: 0.1s; animation-name: zoomIn;">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.3s" src="/MVC/images/Panko_Shrimp.png" style="margin-top: 25%; visibility: visible; animation-delay: 0.3s; animation-name: zoomIn;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.5s" src="/MVC/images/Kani_Salad.png" style="visibility: visible; animation-delay: 0.5s; animation-name: zoomIn;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.7s" src="/MVC/images/Crispy_Crab_Nest.png" style="visibility: visible; animation-delay: 0.7s; animation-name: zoomIn;">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <h5 class="text-start text-success fw-normal">About Us</h5>
                <h2 class="mb-4">Welcome to <i class="fa fa-utensils text-success me-2"></i>Sushilicious</h2>
                <p class="mb-4">
                    Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit.
                    Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.
                    Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit.
                    Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.
                </p>
                <p class="mb-4">
                    Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit.
                    Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.
                </p>

                <div class="row g-4 my-4">
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-success px-3">
                            <div class="ps-4">
                                <p class="mb-0">Instagram</p>
                                <h6 class="mb-0">
                                    <a href="https://www.instagram.com/sushilicious_bh/?hl=en">
                                        @sushilicious.bh
                                    </a>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-success px-3">
                            <div class="ps-4">
                                <p class="mb-0">Phone</p>
                                <h6 class="mb-0">
                                    <a href="tel:+97312345678">
                                        +973 1234 5678
                                    </a>
                                </h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php include 'template/footer.phtml'; ?>
</body>
</html>