<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<div class="container mt-5 mb-5" id="menu">
    <h1>Manage Menu</h1>

    <div class="mt-5 text-center">
        <h6 style="cursor: pointer; font-size: 2rem !important;" onclick="getElementById('newItem').style.display = 'block'">
            <i class="fas fa-plus"></i>
            Add New Item
        </h6>

        <div id="newItem" style="display: none;" >
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="forms" style="font-size: 2rem !important;" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="text" name="name" id="name" tabindex="1" class="form-control" placeholder="Name" value="">
                </div>
                <div class="input-group mb-3">

                    <select name="category" id="category" tabindex="1" class="form-control" value="">
                        <option selected>Category</option>
                        <option value="Salad">Salads</option>
                        <option value="Starter">Starters</option>
                        <option value="Sushi">Sushi</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text">BHD</span>
                    <input type="number" step="0.1" name="price" id="price" tabindex="1" class="form-control" placeholder="Price" value="">
                </div>
                <div class="form-group">
                    <input type="file" name="image" id="image" tabindex="1" class="form-control" placeholder="Image" value="">
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-3">
                            <input type="submit" name="add" id="add" tabindex="4" class="form-control btn btn-login" value="Add">
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>

    <ul class="nav nav-tabs mt-5">
        <li class="active">
            <a data-toggle="tab" href="#salad">Salads</a>
        </li>
        <li><a data-toggle="tab" href="#starter">Starters</a></li>
        <li><a data-toggle="tab" href="#sushi">Sushi</a></li>
    </ul>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" >
    <div class="tab-content">
        <div id="salad" class="tab-pane fade in active show">
            <div class="container mt-5 mb-5">
                <div class="row">

                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>
                                Image
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($view->saladsDataSet as $menuData) { ?>
                        <tr>
                            <td>
                                <img src="/MVC/images/<?php echo $menuData->getPicture(); ?>" style="height: 200px; width: auto;">
                            </td>
                            <td>
                                <?php echo $menuData->getName(); ?>
                            </td>
                            <td>
                                BHD <?php echo $menuData->getPrice(); ?>
                            </td>
                            <td>
                                    <input type="hidden" name="removeitem" value="<?php echo $menuData->getID(); ?>" />
                                    <button type="submit" class="btn btn-register bg-danger px-4 py-3">
                                        <i class="fas fa-times fa-xl"></i>
                                    </button>
                            </td>
                        </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
        <div id="starter" class="tab-pane fade">
            <div class="container mt-5 mb-5">
                <div class="row">
                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>
                                Image
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($view->startersDataSet as $menuData) { ?>
                            <tr>
                                <td>
                                    <img src="/MVC/images/<?php echo $menuData->getPicture(); ?>" style="height: 200px; width: auto;">
                                </td>
                                <td>
                                    <?php echo $menuData->getName(); ?>
                                </td>
                                <td>
                                    BHD <?php echo $menuData->getPrice(); ?>
                                </td>
                                <td>
                                    <input type="hidden" name="removeitem" value="<?php echo $menuData->getID(); ?>" />
                                    <button type="submit" class="btn btn-register bg-danger px-4 py-3">
                                        <i class="fas fa-times fa-xl"></i>
                                    </button>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div id="sushi" class="tab-pane fade">
            <div class="container mt-5 mb-5">
                <div class="row">
                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>
                                Image
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($view->sushiDataSet as $menuData) { ?>
                            <tr>
                                <td>
                                    <img src="/MVC/images/<?php echo $menuData->getPicture(); ?>" style="height: 200px; width: auto;">
                                </td>
                                <td>
                                    <?php echo $menuData->getName(); ?>
                                </td>
                                <td>
                                    BHD <?php echo $menuData->getPrice(); ?>
                                </td>
                                <td>
                                    <input type="hidden" name="removeitem" value="<?php echo $menuData->getID(); ?>" />
                                    <button type="submit" class="btn btn-register bg-danger px-4 py-3">
                                        <i class="fas fa-times fa-xl"></i>
                                    </button>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    </form>
</div>

<?php include 'template/footer.phtml'; ?>
</body>
</html>