<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

    <div class="container my-5 py-5 h-100">
        <form action="checkout.phtml" method="get">
      <div class="row d-flex justify-content-center align-items-center h-100 my-5">
        <div class="col-12">
          <div class="card card-registration card-registration-2" style="border-radius: 15px;">
            <div class="card-body p-0">
              <div class="row g-0">
                <div class="col-lg-8">
                  <div class="p-5">
                    <div class="d-flex justify-content-between align-items-center mb-5">
                      <h1 class="fw-bold mb-0 text-black">Cart</h1>
                      <h6 class="mb-0 text-muted">3 Items</h6>
                    </div>
                    <hr class="my-4">

                    <div class="row mb-4 d-flex justify-content-between align-items-center">
                      <div class="col-md-2 col-lg-2 col-xl-2">
                        <img src="./images/Shrimp_Volcano.png" class="img-fluid rounded-3" >
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-3">
                        <h6 class="text-muted">Sushi</h6>
                        <h4 class="text-black mb-0">Shrimp Volcano</h4>
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                        <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                          <i class="fas fa-minus"></i>
                        </button>

                        <input id="form1" min="0" name="quantity" value="1" type="number"
                               class="form-control form-control-sm" />

                        <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                          <i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                        <h6 class="mb-0">BD 5.00</h6>
                      </div>
                      <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                        <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                      </div>
                    </div>

                    <hr class="my-4">

                    <div class="row mb-4 d-flex justify-content-between align-items-center">
                      <div class="col-md-2 col-lg-2 col-xl-2">
                        <img src="src/Shrimp%20Volcano.png" class="img-fluid rounded-3" >
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-3">
                        <h6 class="text-muted">Sushi</h6>
                        <h4 class="text-black mb-0">Shrimp Volcano</h4>
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                        <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                          <i class="fas fa-minus"></i>
                        </button>

                        <input id="form1" min="0" name="quantity" value="1" type="number"
                               class="form-control form-control-sm" />

                        <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                          <i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                        <h6 class="mb-0">BD 5.00</h6>
                      </div>
                      <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                        <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                      </div>
                    </div>

                    <div class="pt-5">
                      <h6 class="mb-0"><a href="menu.phtml" class="text-body"><i
                              class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 bg-grey">
                  <div class="p-5">
                      <h1 class="fw-bold mb-0 text-black mb-5">Summary</h1>
                    <hr class="my-4">

                    <div class="d-flex justify-content-between mb-5">
                      <h4>Total price</h4>
                      <h4 class="text-danger">BD 12.500</h4>
                    </div>

                    <button type="submit" class="btn btn-register btn-block btn-lg bg-success float-end">CHECKOUT</button>

                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
        </form>
    </div>

<?php include 'template/footer.phtml'; ?>
</body>
</html>