<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<div class="container my-5 py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12">
            <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                <div class="card-body p-0">
                    <div class="row g-0">
                        <div class="col-lg-8">
                            <div class="p-5">
                                <div class="d-flex justify-content-between align-items-center mb-5">
                                    <h1 class="fw-bold mb-0 text-black">Checkout</h1>
                                    <h6 class="mb-0 text-muted">3 Items</h6>
                                </div>
                                <hr class="my-4">

                                <div class="row mb-4 d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                        <img
                                                src="/MVC/images/Shrimp_Volcano.png"
                                                class="img-fluid rounded-3" >
                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <h6 class="text-muted">Sushi</h6>
                                        <h4 class="text-black mb-0">Shrimp Volcano</h4>
                                    </div>
                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                        <h6 class="mb-0">BD 5.00</h6>
                                    </div>
                                </div>

                                <hr class="my-4">

                                <div class="row mb-4 d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                        <img
                                                src="/MVC/images/Burrata_Cheese_Salad.png"
                                                class="img-fluid rounded-3" >
                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <h6 class="text-muted">Salad</h6>
                                        <h4 class="text-black mb-0">Burrata Cheese Salad</h4>
                                    </div>
                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                        <h6 class="mb-0">BD 6.50</h6>
                                    </div>
                                </div>

                                <hr class="my-4">

                                <div class="d-flex justify-content-between mb-5">
                                    <h4>Total price</h4>
                                    <h4 class="text-danger">BD 12.500</h4>
                                </div>

                                <div class="pt-5">
                                    <h6 class="mb-0"><a href="menu.phtml" class="text-body"><i
                                            class="fas fa-long-arrow-alt-left me-2"></i>Back to cart</a></h6>
                                </div>
                            </div>
                        </div>
                            <div class="col-lg-4 bg-grey">
                                <div class="p-5 checkout">
                                    <form>
                                        <h1 class="fw-bold mb-5 text-black">Delivery</h1>
                                        <hr class="my-4">

                                        <h5 class="mb-3">Phone</h5>
                                        <div class="form-group">
                                            <input type="tel" name="phone" id="phone" tabindex="1" class="form-control" placeholder="Phone Number" value="">
                                        </div>

                                        <h5 class="mb-3">Address</h5>

                                        <div class="mb-4 pb-2">
                                            <select class="form-select">
                                                <option value="1">Home - Flat 123, Bldg 234, Blk 111, Riffa</option>
                                                <option value="2">Office - Office 12, Platinum Tower, Seef</option>
                                            </select>
                                        </div>

                                        <div class="mb-5">
                                            <h5 class="mb-0" style="cursor: pointer">
                                                <a onclick="getElementById('newAddress').style.display = 'block'" class="text-body">
                                                    <i class="fas fa-plus me-2"></i>
                                                    Add new address
                                                </a>
                                            </h5>
                                        </div>

                                        <div id="newAddress" style="display: none;">
                                            <div class="form-group">
                                                <input type="text" name="name" id="name" tabindex="1" class="form-control" placeholder="Name" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="block" id="block" tabindex="1" class="form-control" placeholder="Block number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="street" id="street" tabindex="1" class="form-control" placeholder="Street Number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="house" id="house" tabindex="1" class="form-control" placeholder="House Number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="details" id="details" tabindex="1" class="form-control" placeholder="More details" value="">
                                            </div>
                                        </div>

                                        <hr class="my-4">

                                        <button type="submit" class="btn btn-register btn-block btn-lg bg-success">ORDER NOW</button>
                                    </form>

                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include 'template/footer.phtml'; ?>
</body>
</html>