<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<div class="container my-5 py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12">
            <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                <div class="card-body p-0">
                    <div class="row g-0">
                        <div class="col-lg-8">
                            <div class="p-5">
                                <div class="d-flex justify-content-between align-items-center mb-5">
                                    <h1 class="fw-bold mb-0 text-black">Checkout</h1>
                                    <h6 class="mb-0 text-muted">3 Items</h6>
                                </div>
                                <hr class="my-4">
                                <?php $total = 0; foreach($view->cart as $cartSet) { ?>
                                <div class="row mb-4 d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                        <img
                                                src="/MVC/images/<?php echo $cartSet->getPicture(); ?>"
                                                class="img-fluid rounded-3" >
                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <h6 class="text-muted"><?php echo $cartSet->getCategory(); ?></h6>
                                        <h4 class="text-black mb-0"><?php echo $cartSet->getName(); ?></h4>
                                    </div>
                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                        <h6 class="mb-0">BD <?php $pid = $cartSet->getID(); $price = $cartSet->getPrice() * $cartData[$pid]; $total += $price; echo $price; ?></h6>
                                    </div>
                                </div>
                                <hr class="my-4">
                                <?php } ?>

                                <div class="d-flex justify-content-between mb-5">
                                    <h4>Total Price</h4>
                                    <h4 class="text-danger">BD <?php echo $total; ?></h4>
                                </div>

                                <div class="pt-5">
                                    <h6 class="mb-0"><a href="cart.php" class="text-body"><i
                                            class="fas fa-long-arrow-alt-left me-2"></i>Back to cart</a></h6>
                                </div>
                            </div>
                        </div>
                            <div class="col-lg-4 bg-grey">
                                <div class="p-5 checkout">
                                    <form id="checkout" name="checkout" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                                        <h1 class="fw-bold mb-5 text-black">Delivery</h1>
                                        <hr class="my-4">

                                        <h5 class="mb-3">Address</h5>

                                        <div class="mb-4 pb-2">
                                            <select class="form-select" name="address">
                                                <?php foreach($view->addresses as $addressSet) { ?>
                                                <option value="<?php echo $addressSet->getID(); ?>"><?php echo $addressSet->getName(); ?> - <?php echo $addressSet->getBuilding(); ?>, Street <?php echo $addressSet->getStreet(); ?>, Block <?php echo $addressSet->getBlock(); ?>, <?php echo $addressSet->getArea(); ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>

                                        <div class="mb-5">
                                            <h5 class="mb-0" style="cursor: pointer">
                                                <a href="address.php">Add New Address</a>
                                            </h5>
                                        </div>

                                        <div id="newAddress" style="display: none;">
                                            <div class="form-group">
                                                <input type="text" name="name" id="name" tabindex="1" class="form-control" placeholder="Name" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="block" id="block" tabindex="1" class="form-control" placeholder="Block number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="street" id="street" tabindex="1" class="form-control" placeholder="Street Number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="house" id="house" tabindex="1" class="form-control" placeholder="House Number" value="">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="details" id="details" tabindex="1" class="form-control" placeholder="More details" value="">
                                            </div>
                                        </div>

                                        <hr class="my-4">

                                        <button type="submit" class="btn btn-register btn-block btn-lg bg-success">ORDER NOW</button>
                                    </form>

                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include 'template/footer.phtml'; ?>
</body>
</html>