<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<style>
    table {
        font-size: 1.7rem;
    }
</style>

<div class="container d-flex justify-content-center">
    <div class="row text-center forms" style="margin: 150px 0">
        <h1>Order History</h1>
        <p>Re-order your favourite orders now</p>
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>
                        Order no.
                    </th>
                    <th>
                        Order time
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Details
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($view->pastOrders as $ordersData) { ?>
                <tr>
                    <td>
                        <?php echo $ordersData->getID(); ?>
                    </td>
                    <td>
                        <?php echo $ordersData->getDate(); ?>
                    </td>
                    <?php if($ordersData->getStatus() == "successful") { ?>
                    <td>
                        <h6 class="border border-success m-0 px-0  pl-0 py-1 status green">
                            <i class="fas fa-circle text-success fa-xs"></i>
                            Successful
                        </h6>
                    </td>
                    <?php } if($ordersData->getStatus() == "canceled") { ?>
                    <td>
                        <h6 class="border border-danger m-0 px-0  pl-0 py-1 status red">
                            <i class="fas fa-circle text-danger fa-xs"></i>
                            Canceled
                        </h6>
                    </td>
                    <?php } ?>
                    <td>
                        <?php $view->orderItems = $itemsDataSet->fetchOrderItems($ordersData->getID());
                        foreach($view->orderItems as $itemsData) { ?>
                        <h6>
                            <strong><?php echo $itemsData->getQuantity(); ?></strong> x <?php echo $itemsData->getItemName(); ?>
                        </h6>
                    <?php } ?>
                    </td>
                    <td>
                        <a href="">
                            <i class="fas fa-redo-alt fa-lg"></i>
                        </a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'template/footer.phtml'; ?>
