<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<div class="container d-flex justify-content-center align-items-center">
  <div class="row col-md-6 text-center forms" style="margin: 150px 0">
    <h1>Join Now</h1>
    <p>Login or Signup now to order the tastiest sushi in the town</p>

    <div class="tab-content text-center mt-5 forms">
      <div id="login" class="tab-pane fade in active show">
        <form id="login-form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" role="form">
          <div class="form-group">
            <input type="text" name="email" id="em" tabindex="1" class="form-control" placeholder="Email" value="">
          </div>
          <div class="form-group">
            <input type="password" name="password" id="pass" tabindex="2" class="form-control" placeholder="Password">
          </div>
          <div class="form-group text-center">
            <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
            <label for="remember"> Remember Me</label>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-center">
                  <a href="" tabindex="5" class="forgot-password">Forgot Password?</a>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>

<?php include 'template/footer.phtml'; ?>
</body>
</html>