<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Login</title>
    <meta charset="utf-8">
</head>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <button type="submit">Login</button>
    </div>
</form>

</html>
