<!DOCTYPE html>
<html lang="en">
<?php include 'template/header.phtml'; ?>
<body>
<?php include 'template/navigation.phtml'; ?>

<div class="container d-flex justify-content-center align-items-center">
    <div class="row col-md-6 text-center forms" style="margin: 150px 0">
        <h1>Join Now</h1>
        <p>Login or Signup now to order the tastiest sushi in the town</p>


        <form id="register-form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" role="form">
          <div class="form-group">
            <input type="text" name="fname" id="fname" tabindex="1" class="form-control" placeholder="First Name" value="">
          </div>
          <div class="form-group">
            <input type="text" name="lname" id="lname" tabindex="1" class="form-control" placeholder="Last Name" value="">
          </div>
          <div class="form-group">
            <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
          </div>
          <div class="form-group">
            <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
          </div>
          <div class="form-group">
            <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
              </div>
            </div>
          </div>
        </form>
    </div>
</div>


<?php include 'template/footer.phtml'; ?>
</body>
</html>