<!-- Footer -->
<footer class="text-center text-white" style="background-color: #64595d">
    <!-- Grid container -->
    <div class="container">
        <!-- Section: Text -->
        <section class="mb-5 mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
                        distinctio earum repellat quaerat voluptatibus placeat nam,
                        commodi optio pariatur est quia magnam eum harum corrupti
                        dicta, aliquam sequi voluptate quas.
                    </p>
                </div>
            </div>
        </section>
        <!-- Section: Text -->

        <!-- Section: Social -->
        <section class="text-center mb-5">
            <a href="" class="text-white me-4">
                <i class="fab fa-facebook-f fa-lg"></i>
            </a>
            <a href="" class="text-white me-4">
                <i class="fab fa-twitter fa-lg"></i>
            </a>
            <a href="" class="text-white me-4">
                <i class="fab fa-instagram fa-lg"></i>
            </a>
        </section>
        <!-- Section: Social -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="/">Sushilicious</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

<!-- jquery -->
<script src="./js/jquery.js"></script>

<!-- boostrap -->
<script src="./js/bootstrap.js" type="text/javascript" ></script>

