<!-- Footer -->
<footer class="text-center text-white" style="background-color: #64595d">
    <!-- Grid container -->
    <div class="container">
        <!-- Section: Text -->
        <section class="mb-5 mt-5">
            <div class="row d-flex justify-content-center">
            </div>
        </section>

        <!-- Section: Social -->
        <section class="text-center mb-5">
            <a href="" class="text-white me-4">
                <i class="fab fa-facebook-f fa-lg"></i>
            </a>
            <a href="" class="text-white me-4">
                <i class="fab fa-twitter fa-lg"></i>
            </a>
            <a href="" class="text-white me-4">
                <i class="fab fa-instagram fa-lg"></i>
            </a>
        </section>
        <!-- Section: Social -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="/">Sushilicious</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

<!-- jquery -->
<script src="/MVC/js/jquery.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- boostrap -->
<script src="/MVC/js/bootstrap.js" type="text/javascript" ></script>

