<nav class="navbar navbar-expand-lg navbar-light bg-light p-3 mb-0"  id="home">
    <div class="container-fluid ">
        <a href="index.php">
            <img src="/MVC/images/logo-new.png" height="60px" width="auto" alt="banner">
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="home.php" class="nav-item nav-link active">
                    Home
                </a>
                <a href="about.php" class="nav-item nav-link">
                    About
                </a>
                <a href="menu.php" class="nav-item nav-link">
                    Menu
                </a>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="cart.php" class="nav-item nav-link">
                    <i class="fas fa-shopping-cart"></i>
                </a>
                <a href="signup.php" class="nav-item nav-link">
                    Login
                </a>
                <a href="#" class="nav-item nav-link">
                    <strong>
                        Profile
                    </strong>
                </a>
                <a href="#" class="nav-item nav-link">
                    Logout
                </a>
            </div>
        </div>
    </div>
</nav>
